version: '3'
services: 
    nginx:
        build: 
            context: .
            dockerfile: DockerfileNginx
        image: paganuzzi/laravel-nginx:1
        ports: 
            - 8000:8000
        depends_on: 
            - phpfpm
    phpfpm:
        build: 
            context: .
            dockerfile: DockerfilePHP
        image: paganuzzi/laravel-phpfpm:1
