name: Composer
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: composer
        run: |
          cd app
          composer install

      -
        name: Docker meta
        id: meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: paganuzzi/stacklaravel/stacklaravel-php
          tags: |
            type=ref,event=branch
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push php
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: DockerfilePHP
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # tags: |
          #   ghcr.io/paganuzzi/stacklaravel-php:latest