name: Composer
on:
  push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]
    tags:
      - v1.*

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: composer
        run: |
          cd app
          composer install
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: DockerfilePHP
          tags: paganuzzi/laravel-nginx:"${GITHUB_REF#refs/*/}"
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.MYTOKEN }}