name: Composer
on:
  push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]
    tags:
      - v1.*

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: composer
        run: |
          cd app
          composer install
          cd ..
          docker build -t paganuzzi/laravel-nginx:"${GITHUB_SHA}" -f DockerfilePHP .