name: Composer
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: composer
        run: |
          cd app
          echo ${{ secrets.GITHUB_TOKEN }}
      # - name: Build and push
          #composer install
      #   id: docker_build
      #   uses: docker/build-push-action@v2
      #   with:
      #     push: true
      #     context: .
      #     file: ./DockerfilePHP
      #     tags: paganuzzi/laravel-nginx:v1
      #     secrets: |
      #       GIT_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}
