name: Composer
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: composer
        run: |
          cd app
          composer install
      - name: Build and push
        uses: docker/build-push-action:${{GITHUB_REF#refs/*/}}
        id: docker_build
        with:
          push: true
          context: .
          file: ./DockerfilePHP
          tags: paganuzzi/laravel-nginx:1
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}
