name: stacklaravel-nginx
on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: chekout
        uses: actions/checkout@v2

      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push php
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: DockerfilePHP
          tags: ghcr.io/paganuzzi/stacklaravel-nginx:${{ steps.tag.outputs.tag }}